repos:
  - repo: local
    hooks:

      - id: Preserve files
        name: Add changed files for commit
        entry: git add -u
        pass_filenames: false
        language: system
      - id: Formatting
        name: Format code style
        entry: cargo fmt
        pass_filenames: false
        language: system

      - id: Preserve files
        name: Add changed files for commit
        entry: git add -u
        pass_filenames: false
        language: system
