[parts.major]
value = 4
factory.payload = { default = 0 }
factory.name = "increment"


[parts.minor]
value = 16
factory.name = "increment"


[parts.patch]
value = 23
factory.name = "increment"


[parts.stage]
value = "beta"
factory.name = "loop"
factory.payload = ["alpha", "beta"]


[parts.step]
value = 2
factory.name = "increment"


[[files."req.txt"]]
version.view = "{major}.{minor}.{patch}-{stage}{step}"
version.placement = "dep=={version}"


[[files."req.txt"]]
version.view = "{{ major }}.{{ minor }}{% if patch != 0 %}.{{ patch }}{% endif %}"
version.placement = "dep-another-style=={version}"
enable_liquid_tempaltes = true
