[parts.major]
value = 18
factory.payload = { default = 0 }
factory.name = "increment"


[parts.minor]
value = 3
factory.payload = { default = 0 }
factory.name = "increment"


[parts.patch]
value = 2
factory.name = "increment"


[parts.stage]
value = "alpha"
factory.name = "loop"
factory.payload = ["alpha", "beta"]


[parts.step]
value = 0
factory.payload = { default = 0 }
factory.name = "increment

[[files."req.txt"]]
version.view = "{major}.{minor}.{patch}-{stage}{step}"
version.placement = "foobar=={version}"
