[parts.major]
value = 32
factory.payload = { default = 0 }
factory.name = "increment"


[parts.minor]
value = 0
factory.payload = { default = 0 }
factory.name = "increment"


[parts.patch]
value = 0
factory.name = "increment"


[parts.stage]
value = "alpha"
factory.name = "loop"
factory.payload = ["alpha", "beta"]


[parts.step]
value = 0
factory.payload = { default = 0 }
factory.name = "increment"

[[files."req.txt"]]
version.view = "{major}.{minor}.{patch}-{stage}{step}"
version.placement = "foobar=={version}"

[hooks.afterwords]
"Echo something" = ["echo", "!ASK:Enter what to echo"]
"Echo version" = ["echo", "!FORMAT:New version is: {new.major}.{new.minor}.{new.patch}"]
